/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app1;

import java.awt.Button;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cuckoodiles
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        SidebarInit();
        
        List<Map<String, Object>> employees = new ArrayList<>();

        Map<String, Object> emp1 = new LinkedHashMap<>(); // LinkedHashMap → keeps insertion order (nicer in tables)
        emp1.put("id", 1001);
        emp1.put("first_name", "Juan");
        emp1.put("last_name", "Dela Cruz");
        emp1.put("email", "juan.delacruz@company.ph");
        emp1.put("phone", "09171234567");
        emp1.put("department", "IT");
        emp1.put("position", "Software Engineer");
        emp1.put("hire_date", java.sql.Date.valueOf("2022-06-15"));
        emp1.put("monthly_salary", new java.math.BigDecimal("85000.00"));
        emp1.put("is_active", true);
        emp1.put("status", "Regular");

        employees.add(emp1);
        
        String[] columns = {
            "Employee ID", "First Name", "Last Name", 
            "Department", "Position", "Monthly Salary", "Active"
        };

        DefaultTableModel model = new DefaultTableModel(columns, 0);

        for (Map<String, Object> row : employees) {
            model.addRow(new Object[] {
                row.get("id"),
                row.get("first_name"),
                row.get("last_name"),
                row.get("department"),
                row.get("position"),
                row.get("monthly_salary"),
                row.get("is_active"),
                row.get("status"),
            });
        }

        jTable1.setModel(model);
    }
    
    private void SidebarInit() {
        sideBodypnl.setPreferredSize(new Dimension(sidebarpnl.getWidth(), 0));
        
        for(int i = 0; i < 4; i++) {
            final int index = i;
            
            Button btn = new Button("Nav" + i);
            btn.setPreferredSize(new Dimension(sideBodypnl.getWidth(), 50));
            btn.setBackground(Color.red);
            btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    ((CardLayout) outletpnl.getLayout())
                        .show(outletpnl, "page" + (index + 1));
                    System.out.println("Navigate to page " + (index + 1));

                    // highlightSelectedButton(index);
                }
            });         
            
            sideBodypnl.add(btn);
        }
        
        sideBodypnl.revalidate();
        sideBodypnl.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpnl = new javax.swing.JPanel();
        sidebarpnl = new javax.swing.JPanel();
        sideHeaderpnl = new javax.swing.JPanel();
        sideBodypnl = new javax.swing.JPanel();
        outletpnl = new javax.swing.JPanel();
        page1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        page2 = new javax.swing.JPanel();
        page3 = new javax.swing.JPanel();
        page4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainpnl.setBackground(new java.awt.Color(204, 255, 204));
        mainpnl.setLayout(new java.awt.BorderLayout());

        sidebarpnl.setBackground(new java.awt.Color(255, 255, 204));
        sidebarpnl.setPreferredSize(new java.awt.Dimension(150, 552));
        sidebarpnl.setLayout(new java.awt.BorderLayout());

        sideHeaderpnl.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout sideHeaderpnlLayout = new javax.swing.GroupLayout(sideHeaderpnl);
        sideHeaderpnl.setLayout(sideHeaderpnlLayout);
        sideHeaderpnlLayout.setHorizontalGroup(
            sideHeaderpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        sideHeaderpnlLayout.setVerticalGroup(
            sideHeaderpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        sidebarpnl.add(sideHeaderpnl, java.awt.BorderLayout.PAGE_START);

        sideBodypnl.setBackground(new java.awt.Color(255, 204, 204));
        sidebarpnl.add(sideBodypnl, java.awt.BorderLayout.CENTER);

        mainpnl.add(sidebarpnl, java.awt.BorderLayout.LINE_START);

        outletpnl.setBackground(new java.awt.Color(204, 255, 204));
        outletpnl.setLayout(new java.awt.CardLayout());

        page1.setBackground(new java.awt.Color(0, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout page1Layout = new javax.swing.GroupLayout(page1);
        page1.setLayout(page1Layout);
        page1Layout.setHorizontalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );
        page1Layout.setVerticalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );

        outletpnl.add(page1, "page1");

        page2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout page2Layout = new javax.swing.GroupLayout(page2);
        page2.setLayout(page2Layout);
        page2Layout.setHorizontalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        page2Layout.setVerticalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        outletpnl.add(page2, "page2");

        page3.setBackground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout page3Layout = new javax.swing.GroupLayout(page3);
        page3.setLayout(page3Layout);
        page3Layout.setHorizontalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        page3Layout.setVerticalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        outletpnl.add(page3, "page3");

        page4.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout page4Layout = new javax.swing.GroupLayout(page4);
        page4.setLayout(page4Layout);
        page4Layout.setHorizontalGroup(
            page4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        page4Layout.setVerticalGroup(
            page4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        outletpnl.add(page4, "page4");

        mainpnl.add(outletpnl, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainpnl;
    private javax.swing.JPanel outletpnl;
    private javax.swing.JPanel page1;
    private javax.swing.JPanel page2;
    private javax.swing.JPanel page3;
    private javax.swing.JPanel page4;
    private javax.swing.JPanel sideBodypnl;
    private javax.swing.JPanel sideHeaderpnl;
    private javax.swing.JPanel sidebarpnl;
    // End of variables declaration//GEN-END:variables
}
